services:
  - type: web
    name: my_webapp
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/yahia-adam/cloud_static_app
    branch: main
    region: frankfurk
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          - name: appdb
          - property: connectionString

databases:
  - name: appdb
    region: frankfurk