services:
  - name: clound-app
    type: web
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    region: frankfurt
    plan: free
    repo: https://github.com/yahia-adam/test_render
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydatabase
          property: connectionString

databases:
  - name: mydatabase
    region: frankfurt
    plan: free
