services:
  - type: web
    name: my_webapp
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/yahia-adam/cloud_static_app
    branch: main
    region: frankfurt
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          - name: mydatabase
          - property: connectionString

databases:
  - name: mydatabase
    plan: free
    region: frankfurt